pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
			./deployment/appBuild/mvn.sh mvn -B -DskipTests clean package
			./deployment/appBuild/build.sh
                    '''   
            }
            post {
                success {
                    archiveArtifacts artifacts: './target/*.jar', fingerprint: true
                }
            }
        }
    }
}
