pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
            pwd
            ls
			./build/mvn.sh mvn -B -DskipTests clean package
			./build/build.sh
           
                    '''   
            }
            post {
                success {
                    archiveArtifacts artifacts: '../target/*.jar', fingerprint: true
                }
            }
        }
    }
}
